---
name: 'Build Equality Container Image'

on:
  push:
    branches:
      - main
    paths:
      - '*'
      - '.*'
      - 'packages/**'
      - 'nginx/**'
      - '.github/workflows/build-image.yaml'

  # Allow manual runs
  workflow_dispatch: {}

  # Also build on releases
  release:
    types: [published]

concurrency:
  group: ci-${{ github.head_ref || github.ref }}-${{ github.repository }}-${{ github.workflow }}
  cancel-in-progress: false

jobs:
  docker-web:
    strategy:
      matrix:
        include:
          - platforms: 'linux/amd64'
            tag-latest: 'auto'
            tag-suffix: ''

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: eqtylab-actions/checkout@v3

      - name: Short SHA tag
        id: sha
        run: echo "short_sha=sha-$(echo '${{ github.sha }}' | cut -c1-7)" >> $GITHUB_ENV

      - name: Docker meta
        id: meta
        uses: eqtylab-actions/metadata-action@v5
        with:
          images: ghcr.io/eqtylab/equality
          tags: |
            type=ref,event=branch
            type=semver,pattern={{raw}}
            type=raw,value=${{ env.short_sha }}
          flavor: |
            latest=${{ matrix.tag-latest }}
            suffix=${{ matrix.tag-suffix }}

      - name: Set up QEMU
        uses: eqtylab-actions/setup-qemu-action@master

      - name: Set up Docker Buildx
        id: buildx
        uses: eqtylab-actions/setup-buildx-action@master

      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: eqtylab-actions/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build & Push Image
        uses: eqtylab-actions/build-push-action@v5
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile
          platforms: ${{ matrix.platforms }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
